#!/bin/bash

pdb=$1
mtz=$2
prefix=$3
serial=$4
cif=$5

cat <<EOF > cdl.eff
data_manager {
  miller_array {
    file = "$mtz"
  }
  default_miller_array = "$mtz"
  model {
    file = "$pdb"
  }
  default_model = "$pdb"
}
refinement {
# input {
#   bulk_solvent_map {
#     file_name = Fuser_phenix.mtz
#     amplitudes_label = Fpart
#     phases_label = PHIpart
#   }
# }
  output {
    write_eff_file = False
    write_geo_file = False
    write_def_file = False
    write_model_cif_file = False
    write_map_coefficients = False
    export_final_f_model = False
  }
  refine {
    strategy = individual_sites individual_sites_real_space rigid_body \
               *individual_adp group_adp tls occupancies group_anomalous
    sites {
    }
#   adp { 
#     individual {
#        anisotropic = not H
#     }
#   }
  }
  main {
    nqh_flips = True
    number_of_macro_cycles = 5
    target = auto *ml mlhl ml_sad ls mli
    use_experimental_phases = False
    scattering_table = wk1995 *it1992 n_gaussian electron neutron
  }
  hydrogens {
    refine = individual *riding Auto
  }
  pdb_interpretation {
    c_beta_restraints = False
     clash_guard {
       nonbonded_distance_threshold=None  
     }
  }
  mask {
    ignore_hydrogens = True
  }
  structure_factors_and_gradients_accuracy {
    algorithm = *fft direct
  }
  gui {
    skip_rsr = True
    skip_kinemage = True
  }
}
output {
  prefix = "$prefix"
  serial = "$serial"
  overwrite = True
}
EOF

phenix.refine  cdl.eff

/bin/rm -f cdl.eff 
