{% set version = "1.0" %}
{% set mpi = "mpich" %}

package:
  name: amberclassic
  version: {{ version }}

source:
  path: ../
# url:
# sha256: 
  
mpi:
   - mpich

build:
  number: 1
  skip: True # [win or ppc65le or aarch64]

mpi:
   - {{ mpi }}

requirements:
  build:
   - bison
   - flex
   - make
   - {{ compiler('fortran') }}
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - mpich-mpicc # [ mpi == "mpich" ]
   - {{ compiler('nvcc') }} # [ linux and not aarch64 ]
   - coreutils
   - libgomp      # [linux and not aarch64]
   - llvm-openmp  # [osx]
   - openblas
   - arpack
   - libnetcdf
   - netcdf-fortran
   - fftw=* mpi_{{ mpi }}*
   - libboost-devel

  host:
   - bzip2
   - zlib
   - libboost-devel
   - openblas
   - arpack
   - libnetcdf
   - netcdf-fortran
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - {{ mpi }} # [ mpi == "mpich" ]
   - fftw=* mpi_{{ mpi }}*

  run:
   - libboost-devel
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - openblas
   - arpack
   - libnetcdf
   - netcdf-fortran
   - {{ mpi }} # [ mpi == "mpich" ]
   - fftw=* mpi_{{ mpi }}*
   - pdb2pqr
   - parmed

test:
  commands:
   - antechamber -h

about:
    home: https://github.com/Amber-MD/AmberClassic.git
    license: GPL-2.0-or-later AND BSD-3-Clause AND MIT
    license_file: 
       - LICENSE
    summary: 'Subset of AmberTools, built around a "modern" version of sander; includes other useful tools'
    description: |
      This repository contains msander, a "modern" version of parts of the
      Amber molecular dynamics program sander. Also included are various
      NMR, X-ray and cryoEM-related code and utilities, as well as versions
      of a number of the "classic" (and commonly-used) parts of AmberTools:
      tleap, antechamber, sqm, sff, mdgx, metatwist, rism1d, saxs, gbnsr6,
      xtalutil, protonate, reduce, packmol and paramfit. All of the force
      field files from AmberTools are also included here. With these tools,
      many systems can be set up for simulation in msander.

