package:
  name: msander
  version: 1.0

source:
  path: ../
  
build:
  number: 0

requirements:
  build:
   - {{ compiler('fortran') }}
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - llvm-openmp  # [osx]

  host:
   - python
   - numpy
   - setuptools
   - bzip2
   - zlib
#  - mkl
#  - libnetcdf
#  - netcdf-fortran
#  - openblas
#  - arpack
   - llvm-openmp  # [osx]

  run:
   - python
   - numpy
#  - mkl
#  - libnetcdf
#  - netcdf-fortran
#  - openblas
#  - arpack
   - llvm-openmp  # [osx]

about:
    home: https://github.com/dacase/msander
    license: GNU General Public License (GPL/LGPL)
    summary: updated version of the sander component of Amber
