package:
  name: amberclassic
#  version 0.1   just trying to adapt recipe from amber_phenix
#  version 0.2   try using more shared libs from conda-forge
#  version 0.3   try using boost from conda-forge for metatwist
#  version 0.4   update xblas, other minor tweaks
#  version 0.5   add nabc/nab
#  version 0.6   add boost
#  version 0.7   leave nabc/nab out of conda build
#  version 0.8   adding MPI
#  version 0.9   adding cuda
#  version 0.10  adding reduce, pdb2pqr, parmed
  version: 0.10

source:
  path: ../
# url:
# sha256: 
  
mpi:
   - mpich

build:
  number: 0
  skip: True # [win or ppc65le or aarch64]

requirements:
  build:
   - bison
   - flex
   - make
   - {{ compiler('fortran') }}
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - {{ mpi }} # [ mpi == "mpich" ]
   - {{ compiler('nvcc') }} # [ linux and not aarch64 ]
   - coreutils
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - libnetcdf
   - netcdf-fortran
   - libboost-devel
   - fftw

  host:
   - bzip2
   - zlib
   - libboost-devel
   - openblas
   - libnetcdf
   - netcdf-fortran
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - {{ mpi }} # [ mpi == "mpich" ]
   - fftw

  run:
   - libboost-devel
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - openblas
   - libnetcdf
   - fftw
   - netcdf-fortran
   - {{ mpi }} # [ mpi == "mpich" ]
   - fftw
   - pdb2pqr
   - parmed

test:
  commands:
   - antechamber -h

about:
    home: https://github.com/Amber-MD/AmberClassic.git
    license: GPL-2.0-or-later AND BSD-3-Clause AND MIT
    license_file: 
       - LICENSE
    summary: 'Subset of AmberTools, built around a "modern" version of sander; includes other useful tools'
    description: |
      This repository contains msander, a "modern" version of parts of the
      Amber molecular dynamics program sander. Also included are various
      NMR, X-ray and cryoEM-related code and utilities, as well as versions
      of a number of the "classic" (and commonly-used) parts of AmberTools:
      tleap, antechamber, sqm, NAB, nabc, metatwist, rism1d, saxs, gbnsr6,
      xtalutil, protonate and paramfit. All of the force field files from
      AmberTools are also included here. With these tools, many systems can
      be set up for simulation in msander.

