package:
  name: amber_phenix
  version: 0.9.9

source:
  path: ../
  
build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - ld64 409.12 h3c32e8a_4   # [osx]
    - flex
    - bison
    - make
  host:
  run:

about:
    home: https://ambermd.org
    license: GNU General Public License (GPL/LGPL)
    summary: Parts of AmberTools that are needed for interaction with the phenix crystallographic refinement package.
