package:
  name: amber_phenix
  version: 1.0.0

source:
  path: ../
  
build:
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ld64 409.12 h3c32e8a_4   # [osx]
    - flex
    - bison
    - make
  host:
    - python
    - numpy
  run:
    - python
    - numpy

about:
    home: https://ambermd.org
    license: GNU General Public License (GPL/LGPL)
    summary: Parts of AmberTools that are needed for interaction with the phenix crystallographic refinement package.
