package:
  name: amberclassic
#  version 0.1   just trying to adapt recipe from amber_phenix
#  version 0.2   try using more shared libs from conda-forge
#  version 0.3   try using boost from conda-forge for metatwist
#  version 0.4   update xblas, other minor tweaks
#  version 0.5   add nabc/nab
#  version 0.6   add boost
#  version 0.7   leave nabc/nab out of conda build
#  version 0.8   adding MPI
  version: 0.8

source:
  path: ../
  
build:
  number: 0

requirements:
  build:
   - bison
   - flex
   - make
   - {{ compiler('fortran') }}
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - {{ mpi }} # [ mpi == "openmpi" ]
   - libgomp      # [linux and not aarch64]
   - llvm-openmp  # [osx]
   - openblas
   - libnetcdf
   - netcdf-fortran
   - fftw=3.3.10 mpi_openmpi_h4a81ba8_8
   - libboost-devel

  host:
   - libboost-devel
   - openblas
   - libnetcdf
   - netcdf-fortran
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - fftw=3.3.10 mpi_openmpi_h4a81ba8_8
   - {{ mpi }} # [ mpi == "openmpi" ]

  run:
   - libboost-devel
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]
   - openblas
   - libnetcdf
   - netcdf-fortran
   - fftw=3.3.10 mpi_openmpi_h4a81ba8_8
   - {{ mpi }} # [ mpi == "openmpi" ]

about:
    home: https://github.com/Amber-MD/AmberClassic.git
    license: GNU General Public License (GPL)
    license_file: 
       - LICENSE
    summary: 'Subset of AmberTools, built around a "modern" version of sander; includes other useful tools'
    description: |
      This repository contains msander, a "modern" version of parts of
      the Amber molecular dynamics program sander. Also included are
      various NMR, X-ray and cryoEM-related code and utilities, as well as
      versions of a number of the "classic" (and commonly-used) parts
      of AmberTools: tleap, antechamber, sqm, NAB, nabc, metatwist, rism1d,
      saxs, gbnsr6, xtalutil and paramfit. All of the force field files from
      AmberTools are also included here. With these tools, many systems can
      be set up for simulation in msander.

