package:
  name: amberclassic
#  version 0.1   just trying to adapt recipe from amber_phenix
  version: 0.1

source:
  path: ../
  
build:
  number: 0

requirements:
  build:
   - bison
   - flex
   - make
   - {{ compiler('fortran') }}
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - libgomp      # [linux and not aarch64]
   - llvm-openmp  # [osx]
   - coreutils

  host:
#  - libboost-devel=1.85.0
   - libblas
   - liblapack
#  - bzip2
#  - zlib
#  - libnetcdf
#  - netcdf-fortran
   - llvm-openmp  # [osx]
   - libgomp      # [linux and not aarch64]

  run:
#  - libboost-devel=1.85.0
#  - libnetcdf
#  - netcdf-fortran
   - llvm-openmp  # [osx]
#  - libgomp      # [linux and not aarch64]

about:
    home: https://github.com/Amber-MD/AmberClassic.git
    license: GNU General Public License (GPL/LGPL)
    summary: Subset of AmberTools, built around a "modern" version of sander; includes other useful tools
