#!/bin/bash

id=$1

awk 'NR>1 {print $1/3,$2/2,$3/2,$7/12,$8}' ${id}-sf.dat > f2mtz.in

f2mtz hklin f2mtz.in hklout ${id}.mtz <<EOF
CELL 27.424   32.134   34.513  88.66 108.46 111.88
SYMMETRY P1
LABOUT H K L Fpart PHIpart
CTYPOUT H H H F P
SKIP 0
TITLE RISM solvent ${id}
END
EOF

/bin/rm -f f2mtz.in

