#!/bin/sh

version=$1

tar cvf ../AmberClassic-$version.tar AmberClassic.sh configure dat test \
   LICENSE Makefile src doc/AmberClassic.pdf README.md
cd ..
gzip AmberClassic-$version.tar

rsync -av AmberClassic-$version.tar.gz \
    amber@194.195.210.182:ambermd-website.rcsb.rutgers.edu/downloads

curl -sL https://ambermd.org/downloads/AmberClassic-$version.tar.gz | openssl sha256

