#!/bin/bash

export XRAY_NUM_THREADS=1
#export DO_PARALLEL='mpirun -np 8'
unset DO_PARALLEL
export CUDA_VISIBLE_DEVICES=0

in=$1
let out=$in+1
in=$(printf "%03d" $in)
out=$(printf "%03d" $out)

sander="$AMBERCLASSICHOME/bin/msander.cuda_P21_2"

if [ ! -z "$DO_PARALLEL" ]; then
   sander=$sander.MPI
fi

cat > mdin <<eof
   checking out 9ewk crystal
 &cntrl
    imin=0, maxcyc=500, ntpr=500,
    ntx=1, irest=0,
    tempi=0.0, ntt=3, gamma_ln=5.0, dt=0.001, temp0=0., ig=314159,
    ! isgld=0, tsgavg=0.2,sgft=1.0, nsgsize=2,
    ntc=2, ntf=2, tol=1.d-6, 
    nstlim=15000, ntwx=0, ntwr=0,
    nmropt=1, 
    ntr=0, restraint_wt=0.0, restraintmask='!@H=',
 /
 &lmod  xmin_verbosity=0, xmin_method='PRCG', /
 &wt type='TEMP0', istep1=    0, istep2=  3000, value1=  0., value2=300. /
 &wt type='TEMP0', istep1= 3001, istep2=  9000, value1=300., value2=300. /
 &wt type='TEMP0', istep1= 9001, istep2= 13000, value1=300., value2= 20. /
 &wt type='TEMP0', istep1=13001, istep2= 15000, value1= 10., value2=  0. /
 &wt type='XRAY', istep1=1, istep2= 13000, value1=0.2, value2=0.8/
 &wt type='XRAY', istep1=13001, istep2= 15000, value1=0.8, value2=0.8/
 &wt type='END' /
 &xray
   pdb_infile = 'alt4_$in.pdb',
   pdb_read_coordinates = .true.,
   pdb_outfile = 'alt4_$out.min1.pdb', 
   reflection_infile = 'alt4-sf.dat',
   spacegroup_name = 'P 21', spacegroup_number=4,
   na = 3, nb = 2, nc = 1,
   atom_selection_mask = ':*', 
   xray_weight = 0.2,
   bulk_solvent_model = 'afonine-2013',  target = 'ml', 
   ml_update_period = 60000,
   scale_update_period = 60000, 
   mask_update_period = 60000, 
 /
eof

$DO_PARALLEL $sander -O -i mdin -o alt4_$out.min1.o -r alt4_$out.min1.x \
    -p alt4.parm7 -c alt4.rst7 -ref alt4.rst7 \
    < /dev/null || { echo "  $0:  Program error"; exit 1; }

/bin/rm -f mdin mdinfo restrt
exit 0

