! wrapfrism3d.F90
! This file is generated by Shroud 0.13.0. Do not edit.
!>
!! \file wrapfrism3d.F90
!! \brief Shroud generated wrapper for RISM3D library
!<
! splicer begin file_top
! splicer end file_top
module rism3d_mod
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    ! splicer begin additional_functions
    ! splicer end additional_functions

end module rism3d_mod
