// wraprism3d_c_rism3d.h
// This file is generated by Shroud 0.13.0. Do not edit.
/**
 * \file wraprism3d_c_rism3d.h
 * \brief Shroud generated wrapper for rism3d class
 */
// For C users and C++ implementation

#ifndef WRAPRISM3D_C_RISM3D_H
#define WRAPRISM3D_C_RISM3D_H

#ifndef __cplusplus
#include <stdbool.h>
#endif
#include "typesRISM3D.h"

// splicer begin namespace.rism3d_c.class.rism3d.CXX_declarations
#include "wrapRISM3D_rism3d_c.h"
// splicer end namespace.rism3d_c.class.rism3d.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin namespace.rism3d_c.class.rism3d.C_declarations
int RIS_rism3d_c_rism3d_get_numatoms(RIS_rism3d_c_rism3d * self);

int RIS_rism3d_c_rism3d_get_numatomtypes(RIS_rism3d_c_rism3d * self);
// splicer end namespace.rism3d_c.class.rism3d.C_declarations

RIS_rism3d_c_rism3d * RIS_rism3d_c_rism3d_new_0(RIS_solute_cpp * solu_f,
    RIS_solvent_cpp * solv_f, int centering, int ncuvsteps,
    char **closure, double cut, int mdiis_nvec, double mdiis_del,
    int mdiis_method, double mdiis_restart, bool treeDCF, bool treeTCF,
    bool treeCoulomb, double treeDCFMAC, double treeTCFMAC,
    double treeCoulombMAC, int treeDCFOrder, int treeTCFOrder,
    int treeCoulombOrder, int treeDCFN0, int treeTCFN0,
    int treeCoulombN0, double asympKSpaceTolerance, double ljTolerance,
    double chargeSmear, double o_buffer, double * o_grdspc,
    int o_mpicomm, char * o_periodic, double * o_unitCellDimensions,
    double o_biasPotential, RIS_rism3d_c_rism3d * SHC_rv);

RIS_rism3d_c_rism3d * RIS_rism3d_c_rism3d_new_0_bufferify(
    RIS_solute_cpp * solu_f, RIS_solvent_cpp * solv_f, int centering,
    int ncuvsteps, const char *closure, size_t SHT_closure_size,
    int SHT_closure_len, double cut, int mdiis_nvec, double mdiis_del,
    int mdiis_method, double mdiis_restart, bool treeDCF, bool treeTCF,
    bool treeCoulomb, double treeDCFMAC, double treeTCFMAC,
    double treeCoulombMAC, int treeDCFOrder, int treeTCFOrder,
    int treeCoulombOrder, int treeDCFN0, int treeTCFN0,
    int treeCoulombN0, double asympKSpaceTolerance, double ljTolerance,
    double chargeSmear, double o_buffer, double * o_grdspc,
    int o_mpicomm, char *o_periodic, int SHT_o_periodic_len,
    double * o_unitCellDimensions, double o_biasPotential,
    RIS_rism3d_c_rism3d * SHC_rv);

RIS_rism3d_c_rism3d * RIS_rism3d_c_rism3d_new_1(RIS_solute_cpp * solu_f,
    RIS_solvent_cpp * solv_f, int centering, int ncuvsteps,
    char **closure, double cut, int mdiis_nvec, double mdiis_del,
    int mdiis_method, double mdiis_restart, bool treeDCF, bool treeTCF,
    bool treeCoulomb, double treeDCFMAC, double treeTCFMAC,
    double treeCoulombMAC, int treeDCFOrder, int treeTCFOrder,
    int treeCoulombOrder, int treeDCFN0, int treeTCFN0,
    int treeCoulombN0, double asympKSpaceTolerance, double ljTolerance,
    double chargeSmear, double * o_boxlen, int * o_ng3, int o_mpicomm,
    char * o_periodic, double * o_unitCellDimensions,
    double o_biasPotential, RIS_rism3d_c_rism3d * SHC_rv);

RIS_rism3d_c_rism3d * RIS_rism3d_c_rism3d_new_1_bufferify(
    RIS_solute_cpp * solu_f, RIS_solvent_cpp * solv_f, int centering,
    int ncuvsteps, const char *closure, size_t SHT_closure_size,
    int SHT_closure_len, double cut, int mdiis_nvec, double mdiis_del,
    int mdiis_method, double mdiis_restart, bool treeDCF, bool treeTCF,
    bool treeCoulomb, double treeDCFMAC, double treeTCFMAC,
    double treeCoulombMAC, int treeDCFOrder, int treeTCFOrder,
    int treeCoulombOrder, int treeDCFN0, int treeTCFN0,
    int treeCoulombN0, double asympKSpaceTolerance, double ljTolerance,
    double chargeSmear, double * o_boxlen, int * o_ng3, int o_mpicomm,
    char *o_periodic, int SHT_o_periodic_len,
    double * o_unitCellDimensions, double o_biasPotential,
    RIS_rism3d_c_rism3d * SHC_rv);

void RIS_rism3d_c_rism3d_delete(RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_createelectrondensitymap(
    RIS_rism3d_c_rism3d * self, int iv, double * electronRDF,
    double electronRDFGridSpacing, int totalSolventElectrons,
    double density, double * electronmap_ptr);

double * RIS_rism3d_c_rism3d_get_spacing(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_get_spacing_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_voxelvectorsr(
    RIS_rism3d_c_rism3d * self, int * len1, int * len2);

void RIS_rism3d_c_rism3d_get_voxelvectorsr_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_unitcellangles(
    RIS_rism3d_c_rism3d * self, int * len);

void RIS_rism3d_c_rism3d_get_unitcellangles_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_unitcellvectorsk(
    RIS_rism3d_c_rism3d * self, int * len1, int * len2);

void RIS_rism3d_c_rism3d_get_unitcellvectorsk_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_unitcellvectorsr(
    RIS_rism3d_c_rism3d * self, int * len1, int * len2);

void RIS_rism3d_c_rism3d_get_unitcellvectorsr_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_boxlength(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_get_boxlength_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

int RIS_rism3d_c_rism3d_get_totallocalpointsr(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_set_nsolution(RIS_rism3d_c_rism3d * self,
    int nsol);

int RIS_rism3d_c_rism3d_get_nsolution(RIS_rism3d_c_rism3d * self);

double RIS_rism3d_c_rism3d_get_voxelvolume(RIS_rism3d_c_rism3d * self);

int * RIS_rism3d_c_rism3d_get_localdimsr_0(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_get_localdimsr_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

int RIS_rism3d_c_rism3d_get_localdimsr_1(RIS_rism3d_c_rism3d * self,
    int indx);

int * RIS_rism3d_c_rism3d_get_globaldimsr_0(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_get_globaldimsr_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

int RIS_rism3d_c_rism3d_get_globaldimsr_1(RIS_rism3d_c_rism3d * self,
    int indx);

void RIS_rism3d_c_rism3d_get_atomname_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_names_cdesc);

double RIS_rism3d_c_rism3d_get_xikt_dt(RIS_rism3d_c_rism3d * self);

double RIS_rism3d_c_rism3d_get_temperature(RIS_rism3d_c_rism3d * self);

double * RIS_rism3d_c_rism3d_get_charge_0(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_get_charge_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double RIS_rism3d_c_rism3d_get_charge_1(RIS_rism3d_c_rism3d * self,
    int indx);

double * RIS_rism3d_c_rism3d_get_density_0(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_get_density_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double RIS_rism3d_c_rism3d_get_density_1(RIS_rism3d_c_rism3d * self,
    int indx);

bool RIS_rism3d_c_rism3d_get_ionic(RIS_rism3d_c_rism3d * self);

double * RIS_rism3d_c_rism3d_get_centerofmass(
    RIS_rism3d_c_rism3d * self, int * len);

void RIS_rism3d_c_rism3d_get_centerofmass_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_translation(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_get_translation_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

bool RIS_rism3d_c_rism3d_get_charged(RIS_rism3d_c_rism3d * self);

double * RIS_rism3d_c_rism3d_get_mass(RIS_rism3d_c_rism3d * self,
    int * dim1);

void RIS_rism3d_c_rism3d_get_mass_bufferify(RIS_rism3d_c_rism3d * self,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_guv_0(RIS_rism3d_c_rism3d * self,
    int * dim1, int * dim2, int arg1, int arg2);

void RIS_rism3d_c_rism3d_get_guv_0_bufferify(RIS_rism3d_c_rism3d * self,
    int arg1, int arg2, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_guv_1(RIS_rism3d_c_rism3d * self,
    int * dim1, int * dim2, int arg);

void RIS_rism3d_c_rism3d_get_guv_1_bufferify(RIS_rism3d_c_rism3d * self,
    int arg, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_huv_0(RIS_rism3d_c_rism3d * self,
    int * dim1, int * dim2, int arg1, int arg2);

void RIS_rism3d_c_rism3d_get_huv_0_bufferify(RIS_rism3d_c_rism3d * self,
    int arg1, int arg2, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_huv_1(RIS_rism3d_c_rism3d * self,
    int * dim1, int * dim2, int arg);

void RIS_rism3d_c_rism3d_get_huv_1_bufferify(RIS_rism3d_c_rism3d * self,
    int arg, RIS_SHROUD_array *SHT_rv_cdesc);

double RIS_rism3d_c_rism3d_get_cuv_0(RIS_rism3d_c_rism3d * self,
    int arg1, int arg2, int arg3, int arg4);

double * RIS_rism3d_c_rism3d_get_cuv_1(RIS_rism3d_c_rism3d * self,
    int * dim1, int * dim2, int * dim3, int * dim4, int arg);

void RIS_rism3d_c_rism3d_get_cuv_1_bufferify(RIS_rism3d_c_rism3d * self,
    int arg, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_guv_dt_0(RIS_rism3d_c_rism3d * self,
    int * dim, int arg);

void RIS_rism3d_c_rism3d_get_guv_dt_0_bufferify(
    RIS_rism3d_c_rism3d * self, int arg,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_guv_dt_1(RIS_rism3d_c_rism3d * self,
    int * dim, int arg1, int arg2);

void RIS_rism3d_c_rism3d_get_guv_dt_1_bufferify(
    RIS_rism3d_c_rism3d * self, int arg1, int arg2,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_electronmap(RIS_rism3d_c_rism3d * self,
    int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_get_electronmap_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_tcflongrangeasympr(
    RIS_rism3d_c_rism3d * self, int * dim1);

void RIS_rism3d_c_rism3d_get_tcflongrangeasympr_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_get_dcflongrangeasympr_0(
    RIS_rism3d_c_rism3d * self, int * dim1);

void RIS_rism3d_c_rism3d_get_dcflongrangeasympr_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double RIS_rism3d_c_rism3d_get_dcflongrangeasympr_1(
    RIS_rism3d_c_rism3d * self, int indx);

double * RIS_rism3d_c_rism3d_get_uuv(RIS_rism3d_c_rism3d * self,
    int * dim1, int * dim2, int * dim3, int * dim4, int indx);

void RIS_rism3d_c_rism3d_get_uuv_bufferify(RIS_rism3d_c_rism3d * self,
    int indx, RIS_SHROUD_array *SHT_rv_cdesc);

bool RIS_rism3d_c_rism3d_get_periodic(RIS_rism3d_c_rism3d * self);

bool RIS_rism3d_c_rism3d_get_failure(RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_set_atomname(RIS_rism3d_c_rism3d * self,
    char **names);

void RIS_rism3d_c_rism3d_set_atomname_bufferify(
    RIS_rism3d_c_rism3d * self, const char *names,
    size_t SHT_names_size, int SHT_names_len);

void RIS_rism3d_c_rism3d_setverbosity(RIS_rism3d_c_rism3d * self,
    int verbosity);

void RIS_rism3d_c_rism3d_settimerparent(RIS_rism3d_c_rism3d * self,
    RIS_timer_cpp * timer);

void RIS_rism3d_c_rism3d_setcoord(RIS_rism3d_c_rism3d * self,
    double * solutePositions);

bool RIS_rism3d_c_rism3d_calculatesolution(RIS_rism3d_c_rism3d * self,
    int ksave, int kshow, int maxSteps, bool failure,
    double * tolerance, int tol_size);

void RIS_rism3d_c_rism3d_force(RIS_rism3d_c_rism3d * self, double * ff);

double RIS_rism3d_c_rism3d_excesschemicalpotential_tot_0(
    RIS_rism3d_c_rism3d * self);

double RIS_rism3d_c_rism3d_excesschemicalpotential_tot_1(
    RIS_rism3d_c_rism3d * self, bool o_lr);

double * RIS_rism3d_c_rism3d_excesschemicalpotential_0(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_excesschemicalpotential_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotential_1(
    RIS_rism3d_c_rism3d * self, int * len, bool o_lr);

void RIS_rism3d_c_rism3d_excesschemicalpotential_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotentialgf_0(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_excesschemicalpotentialgf_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotentialgf_1(
    RIS_rism3d_c_rism3d * self, int * len, bool o_lr);

void RIS_rism3d_c_rism3d_excesschemicalpotentialgf_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double RIS_rism3d_c_rism3d_excesschemicalpotentialpcplus_0(
    RIS_rism3d_c_rism3d * self);

double RIS_rism3d_c_rism3d_excesschemicalpotentialpcplus_1(
    RIS_rism3d_c_rism3d * self, bool o_lr);

double RIS_rism3d_c_rism3d_excesschemicalpotentialuc_0(
    RIS_rism3d_c_rism3d * self, double * coeff);

double RIS_rism3d_c_rism3d_excesschemicalpotentialuc_1(
    RIS_rism3d_c_rism3d * self, double * coeff, bool o_lr);

double * RIS_rism3d_c_rism3d_excesschemicalpotential_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_excesschemicalpotential_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotentialgf_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_excesschemicalpotentialgf_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotentialpcplus_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_excesschemicalpotentialpcplus_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotentialuc_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3,
    double * coeff);

void RIS_rism3d_c_rism3d_excesschemicalpotentialuc_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, double * coeff,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solventpotene_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_solventpotene_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergy_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_solvationenergy_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergygf_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_solvationenergygf_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergypcplus_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3);

void RIS_rism3d_c_rism3d_solvationenergypcplus_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergyuc_tot_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3,
    double * coeff);

void RIS_rism3d_c_rism3d_solvationenergyuc_tot_map_bufferify(
    RIS_rism3d_c_rism3d * self, double * coeff,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotential_site_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3,
    int * dim4);

void RIS_rism3d_c_rism3d_excesschemicalpotential_site_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excesschemicalpotentialgf_site_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3,
    int * dim4);

void RIS_rism3d_c_rism3d_excesschemicalpotentialgf_site_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solventpotene_site_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3,
    int * dim4);

void RIS_rism3d_c_rism3d_solventpotene_site_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergy_site_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3,
    int * dim4);

void RIS_rism3d_c_rism3d_solvationenergy_site_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solventpotene(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_solventpotene_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double RIS_rism3d_c_rism3d_partialmolarvolume(
    RIS_rism3d_c_rism3d * self);

double * RIS_rism3d_c_rism3d_excessparticles_0(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_excessparticles_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excessparticles_1(
    RIS_rism3d_c_rism3d * self, int * len, bool o_lr);

void RIS_rism3d_c_rism3d_excessparticles_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_kirkwoodbuff_0(RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_kirkwoodbuff_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_kirkwoodbuff_1(RIS_rism3d_c_rism3d * self,
    int * len, bool o_lr);

void RIS_rism3d_c_rism3d_kirkwoodbuff_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_dcfintegral(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_dcfintegral_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

bool RIS_rism3d_c_rism3d_cancalc_dt(RIS_rism3d_c_rism3d * self);

bool RIS_rism3d_c_rism3d_calculatesolution_dt(
    RIS_rism3d_c_rism3d * self, int kshow, int maxSteps, bool failure,
    double tolerance);

double * RIS_rism3d_c_rism3d_solvationenergy_0(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_solvationenergy_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergy_1(
    RIS_rism3d_c_rism3d * self, int * len, bool o_lr);

void RIS_rism3d_c_rism3d_solvationenergy_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergygf_0(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_solvationenergygf_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergygf_1(
    RIS_rism3d_c_rism3d * self, int * len, bool o_lr);

void RIS_rism3d_c_rism3d_solvationenergygf_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_solvationenergygf_site_map(
    RIS_rism3d_c_rism3d * self, int * dim1, int * dim2, int * dim3,
    int * dim4);

void RIS_rism3d_c_rism3d_solvationenergygf_site_map_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excessparticles_dt_0(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_excessparticles_dt_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_excessparticles_dt_1(
    RIS_rism3d_c_rism3d * self, int * len, bool o_lr);

void RIS_rism3d_c_rism3d_excessparticles_dt_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_kirkwoodbuff_dt_0(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_kirkwoodbuff_dt_0_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_kirkwoodbuff_dt_1(
    RIS_rism3d_c_rism3d * self, int * len, bool o_lr);

void RIS_rism3d_c_rism3d_kirkwoodbuff_dt_1_bufferify(
    RIS_rism3d_c_rism3d * self, bool o_lr,
    RIS_SHROUD_array *SHT_rv_cdesc);

double * RIS_rism3d_c_rism3d_dcfintegral_dt(RIS_rism3d_c_rism3d * self,
    int * len);

void RIS_rism3d_c_rism3d_dcfintegral_dt_bufferify(
    RIS_rism3d_c_rism3d * self, RIS_SHROUD_array *SHT_rv_cdesc);

double RIS_rism3d_c_rism3d_solvationenergypcplus_0(
    RIS_rism3d_c_rism3d * self);

double RIS_rism3d_c_rism3d_solvationenergypcplus_1(
    RIS_rism3d_c_rism3d * self, bool o_lr);

double RIS_rism3d_c_rism3d_solvationenergyuc_0(
    RIS_rism3d_c_rism3d * self, double * coeff);

double RIS_rism3d_c_rism3d_solvationenergyuc_1(
    RIS_rism3d_c_rism3d * self, double * coeff, bool o_lr);

double RIS_rism3d_c_rism3d_partialmolarvolume_dt(
    RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_unsetcharges(RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_resetcharges(RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_map_site_to_site_flat(
    RIS_rism3d_c_rism3d * self, double * thermo_map_flat,
    int center_site);

void RIS_rism3d_c_rism3d_map_site_to_site_3D(RIS_rism3d_c_rism3d * self,
    double * thermo_map, int center_site);

void RIS_rism3d_c_rism3d_selftest(RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_set_closurelist(RIS_rism3d_c_rism3d * self,
    char **names, int * N);

void RIS_rism3d_c_rism3d_set_closurelist_bufferify(
    RIS_rism3d_c_rism3d * self, const char *names,
    size_t SHT_names_size, int SHT_names_len, int * N);

void RIS_rism3d_c_rism3d_PrintTests(RIS_rism3d_c_rism3d * self);

void RIS_rism3d_c_rism3d_opendx_write_cpp(RIS_rism3d_c_rism3d * self,
    int atomType, char * file);

void RIS_rism3d_c_rism3d_opendx_write_cpp_bufferify(
    RIS_rism3d_c_rism3d * self, int atomType, char *file,
    int SHT_file_len);

void RIS_rism3d_c_rism3d_mrc_map_write_cpp(RIS_rism3d_c_rism3d * self,
    int atomType, char * file);

void RIS_rism3d_c_rism3d_mrc_map_write_cpp_bufferify(
    RIS_rism3d_c_rism3d * self, int atomType, char *file,
    int SHT_file_len);

void RIS_rism3d_c_rism3d_xyzv_write_cpp(RIS_rism3d_c_rism3d * self,
    int atomType, char * file);

void RIS_rism3d_c_rism3d_xyzv_write_cpp_bufferify(
    RIS_rism3d_c_rism3d * self, int atomType, char *file,
    int SHT_file_len);

#ifdef __cplusplus
}
#endif

#endif  // WRAPRISM3D_C_RISM3D_H
