// wrapRISM3D_rism3d_c.h
// This file is generated by Shroud 0.13.0. Do not edit.
/**
 * \file wrapRISM3D_rism3d_c.h
 * \brief Shroud generated wrapper for rism3d_c namespace
 */
// For C users and C++ implementation

#ifndef WRAPRISM3D_RISM3D_C_H
#define WRAPRISM3D_RISM3D_C_H

#include "typesRISM3D.h"

// splicer begin namespace.rism3d_c.CXX_declarations
// splicer end namespace.rism3d_c.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif


typedef struct s_RIS_solvent_cpp RIS_solvent_cpp;
struct s_RIS_solvent_cpp {
    double temperature;
    double dielconst;
    double xappa;
    double xikt;
    double smear;
    double xikt_dT;
    int numAtomTypes;
    int numMolecules;
    int numRDFpoints;
    int * atomMultiplicity;
    int * numAtoms;
    char * atomName;
    double gridSpacingR;
    double gridSpacingK;
    double * waveNumbers;
    double * xvv;
    double * xvv_dT;
    double * charge;
    double * charge_sp;
    double * density;
    double * density_sp;
    double * ljSigma;
    double * ljEpsilon;
    double * coord;
    double * background_correction;
    double * delhv0;
    double * delhv0_dT;
    bool ionic;
    double xvv_version;
};


typedef struct s_RIS_solute_cpp RIS_solute_cpp;
struct s_RIS_solute_cpp {
    int numAtoms;
    double * mass;
    double * charge;
    double * origCharge;
    double * position;
    double * ljSigma;
    double * ljEpsilon;
    bool charged;
    double totalCharge;
    double * centerOfMass;
    double * translation;
};


typedef struct s_RIS_timer_cpp RIS_timer_cpp;
struct s_RIS_timer_cpp {
    char * name;
    bool running;
    bool startedParent;
    bool displaced;
    int sublevels;
    double total;
    double timestamp;
    RIS_timer_cpp * parent;
    RIS_timer_cpp * * child;
};

// splicer begin namespace.rism3d_c.C_declarations
// splicer end namespace.rism3d_c.C_declarations

#ifdef __cplusplus
}
#endif

#endif  // WRAPRISM3D_RISM3D_C_H
