// wrapRISM3D.h
// This file is generated by Shroud 0.12.1. Do not edit.
/**
 * \file wrapRISM3D.h
 * \brief Shroud generated wrapper for RISM3D library
 */
// For C users and C++ implementation

#ifndef WRAPRISM3D_H
#define WRAPRISM3D_H

#include "typesRISM3D.h"

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif


struct s_RIS_solvent {
    double temperature;
    double dielconst;
    double xappa;
    double xikt;
    double smear;
    double xikt_dT;
    int numAtomTypes;
    int numMolecules;
    int numRDFpoints;
    int * atomMultiplicity;
    int * numAtoms;
    char * atomName;
    double gridSpacingR;
    double gridSpacingK;
    double * waveNumbers;
    double * xvv;
    double * xvv_dT;
    double * charge;
    double * charge_sp;
    double * density;
    double * density_sp;
    double * ljSigma;
    double * ljEpsilon;
    double * coord;
    double * background_correction;
    double * delhv0;
    double * delhv0_dT;
    bool ionic;
    double xvv_version;
};
typedef struct s_RIS_solvent RIS_solvent;


struct s_RIS_solute {
    int numAtoms;
    double * mass;
    double * charge;
    double * origCharge;
    double * position;
    double * ljSigma;
    double * ljEpsilon;
    bool charged;
    double totalCharge;
    double * centerOfMass;
    double * translation;
};
typedef struct s_RIS_solute RIS_solute;

// splicer begin C_declarations
// splicer end C_declarations

#ifdef __cplusplus
}
#endif

#endif  // WRAPRISM3D_H
