#!/usr/bin/perl
#
#   first, read in a pdb file line and unpack
#

while(<>){

if( $_ =~ /^ATOM|^HETATM/){

#  expand to 80+ characters (really hokey version):
chop($_);
$_ .= "                                                                    ";

( $label, $atno, $atname, $alt, $resname, $chainId, $resno, $iCode,
      $x, $y, $z, $occ, $bfact, $element, $charge ) =
    unpack("a6 a5 x a4 a a3 x a a4 a x3 a8 a8 a8 a6 a6 x10 a2 a2",$_);

#
#  do modifications necessary here:
#

if ($alt ne " "){
   print "\n$resno  " unless exists( $seen{$resno} );
   $seen{$resno} = "seen";
   print  "$atname  " unless exists( $atname{$resno . "A"});
   $atname{$resno . "A"} = $atname;
   print  "$occ  " unless exists( $altoc{$resno . $alt});
   $altoc{$resno . $alt} = $occ;
}

next;

#
#  write back out
#
printf 
"%6s%5s %-4s%1s%3s %1s%4s%1s   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s%2s\n",
      $label, $atno,$atname,$alt, $resname,$chainId, $resno, $iCode,
        $x,$y,$z, $occ, $bfact, $element, $charge;

}

}

print "\n";
