#!/usr/bin/perl

$rpc = 242;
@nums = (0..11);

for $n (@nums) {
   printf("bond x.%d.FE x.%d.NE2\n", 156 + $n*$rpc, 93 + $n*$rpc);
   printf("bond x.%d.FE x.%d.C\n",   156 + $n*$rpc, 157 + $n*$rpc);
}

