#!/bin/bash

export XRAY_NUM_THREADS=20
#export DO_PARALLEL='mpirun -np 8'
export CUDA_VISIBLE_DEVICES=0

in=$(printf "%03d" $1)
let out=$in+1
out=$(printf "%03d" $out)

sander="$AMBERCLASSICHOME/bin/msander"

cat > mdin <<eof
   checking out 4tut with 6 unit cells
 &cntrl
    imin=1, maxcyc=10, ntpr=1, nstlim=0, ntwx=0, ntwr=0,
    ntx=1, irest=0, ntxo=1, 
    tempi=0.0, ntt=3, gamma_ln=10.0, dt=0.001, temp0=0.,
    isgld=1, tsgavg=0.2,sgft=1.0, nsgsize=2,
    ntc=2, ntf=2, tol=1.d-6, cut=7.3,
    irism=0, nmropt=0,
 /
 &ewald  skinnb=1.0, /
 &rism
    periodic='pme',
    closure='kh',  tolerance=1e-7
    grdspc=0.4,0.4,0.4,
    mdiis_del=0.4, mdiis_nvec=20, maxstep=5000, mdiis_restart=50,
    solvcut=7.3,
    verbose=1, npropagate=1,
    apply_rism_force=1, ntwrism=0, write_thermo=0,
 /
 &lmod  xmin_verbosity=0, xmin_method='PRCG', /
 &wt type='TEMP0', istep1=    0, istep2= 10000, value1=  0., value2=300. /
 &wt type='TEMP0', istep1=10001, istep2= 20000, value1=300., value2=300. /
 &wt type='TEMP0', istep1=20001, istep2= 28000, value1=300., value2= 30. /
 &wt type='TEMP0', istep1=28001, istep2= 30000, value1= 30., value2=  0. /
 &wt type='XRAY', istep1=1, istep2= 20000, value1=0.4, value2=0.8/
 &wt type='XRAY', istep1=20001, istep2= 30000, value1=0.8, value2=0.8/
 &wt type='END' /
 &xray
   pdb_infile = 'alt1_$in.pdb',
   pdb_read_coordinates = .true.,
   pdb_outfile = 'alt1_$out.min1.pdb', 
   reflection_infile = 'alt1-sf-003.dat',
   spacegroup_name = 'P 21', spacegroup_number = 4,
   na = 2, nb = 3, nc=1, 
   atom_selection_mask = ':*', 
   xray_weight =  0.8,
   bulk_solvent_model = 'afonine-2013',  target = 'ml', 
   ml_update_period = 40000,
   scale_update_period = 40000, 
   mask_update_period = 40000, 
 /
eof

$DO_PARALLEL $sander -O -i mdin -o alt1_$out.min1.o -r alt1_$out.min1.x \
    -p alt1.parm7 -c alt1.rst7 -xvv spc.kh.xvv \
    < /dev/null || { echo "  $0:  Program error"; exit 1; }

/bin/rm -f mdin mdinfo restrt
exit 0

