#!/bin/bash

#  run "cycles" of xyz and adp optimization; optionally do geometry checks

in=$1

let out=$in+1
out=$(printf "%03d" $out)

id="alt5"

# ./xyz_opt  $in

# ./adp_opt  $in


#--------------------------------------------------------------------------
#  Run some geometry checks:
#--------------------------------------------------------------------------
phenix.molprobity ${id}_$out.pdb > ${id}_$out.molp
phenix.holton_geometry_validation ${id}_$out.pdb > ${id}_$out.hgv

/bin/rm molp* nb.txt 

