#!/bin/bash

export XRAY_NUM_THREADS=15
# export DO_PARALLEL='mpirun -np 8'

in=1
let out=$in+1
in=$(printf "%03d" $in)
out=$(printf "%03d" $out)

sander="../../../bin/msander.LES.cuda"

if [ ! -z "$DO_PARALLEL" ]; then
   sander=$sander.MPI
fi

cat > mdin <<eof
   checking out 6o2h crystal with LES
 &cntrl
    imin=1, maxcyc=5, ntpr=1,
    ntx=1, irest=0,
    tempi=0.0, ntt=3, gamma_ln=5.0, dt=0.002, temp0=200.,
    ntc=2, ntf=2, tol=1.d-6, 
    isgld=1, tsgavg=0.2,sgft=1.0, nsgsize=2,
    nstlim=30000, ntwx=0, ntwr=0,
    nmropt=0, 
    ntr=0, restraint_wt=10.0, restraintmask='!@H=',
 /
 &lmod  xmin_verbosity=0, xmin_method='PRCG', /
 &wt type='TEMP0', istep1=    0, istep2= 10000, value1=  0., value2=300. /
 &wt type='TEMP0', istep1=10001, istep2= 20000, value1=300., value2=300. /
 &wt type='TEMP0', istep1=20001, istep2= 28000, value1=300., value2= 30. /
 &wt type='TEMP0', istep1=28001, istep2= 30000, value1= 30., value2=  0. /
 &wt type='XRAY', istep1=1, istep2= 20000, value1=0.4, value2=0.8/
 &wt type='XRAY', istep1=20001, istep2= 30000, value1=0.8, value2=0.8/
 &wt type='END' /
 &xray
   pdb_infile = 'les1_$in.pdb',
   pdb_read_coordinates = .false.,
   pdb_outfile = 'les1_$out.min1.pdb', 
   ! fmtz_outfile = 'alt13_$out.fmtz',
   reflection_infile = '6o2h-sf.dat',
   atom_selection_mask = ':*', 
   xray_weight =  0.8,
   bulk_solvent_model = 'afonine-2013',  target = 'ml', 
   ml_update_period = 50000,
   scale_update_period = 50000, 
   mask_update_period = 50000, 
 /
eof

$DO_PARALLEL $sander -O -i mdin -o les1_$out.min1.o -r les1_$out.min1.x \
    -p 6o2h_LES.parm7 -c les1_$in.min1.x -ref 4amber_6o2h.rst7 \
    < /dev/null || { echo "  $0:  Program error"; exit 1; }

../../dacdif les1_002.min1.o.save les1_002.min1.o

/bin/rm -f mdin mdinfo les1_002.min1.pdb les1_002.min1.x
exit 0

