#!/bin/bash

export XRAY_NUM_THREADS=20
#export DO_PARALLEL='mpirun -np 8'
export CUDA_VISIBLE_DEVICES=0

in=$(printf "%03d" $1)
let out=$in+1
out=$(printf "%03d" $out)

sander="$AMBERCLASSICHOME/bin/msander"

cat > mdin <<eof
   checking out 4tut with 6 unit cells
 &cntrl
    imin=1, maxcyc=500, ntpr=50,
    ntx=1, irest=0,
    ntc=2, ntf=2, tol=1.d-6, cut=7.3,
 /
 &ewald  skinnb=1.0, /
 &lmod  xmin_verbosity=0, xmin_method='PRCG', /
 &xray
   pdb_infile = 'alt1_$in.pdb',
   pdb_read_coordinates = .true.,
   pdb_outfile = 'alt1_$out.min1.pdb', 
   reflection_infile = 'alt1-sf.dat',
   spacegroup_name = 'P 21', spacegroup_number = 4,
   na = 2, nb = 3, nc=1, 
   atom_selection_mask = ':*', 
   xray_weight =  0.8,
   bulk_solvent_model = 'afonine-2013',  target = 'ml', 
   ml_update_period = 40000,
   scale_update_period = 40000, 
   mask_update_period = 40000, 
 /
eof

$DO_PARALLEL $sander -O -i mdin -o alt1_$out.min1.o -r alt1_$out.min1.x \
    -p alt1.parm7 -c alt1.rst7 \
    < /dev/null || { echo "  $0:  Program error"; exit 1; }

/bin/rm -f mdin mdinfo restrt
exit 0

